### ISSUE TITLE
problem with database as service

### ISSUE THREAD

**Issue by mesolis** [fraoustin/redmine_indicator#13]
Hello! I have a problem installing the plugin because it tells me it cannot connect to the local mysql, it turns out that I have implemented the db as a service (aws)

I looked where I could make the change but I couldn't find it, could you help me with that information?

![redmine_issue](https://user-images.githubusercontent.com/64343565/100637088-3913ed80-3311-11eb-9aea-6d3091ffc586.png)

**Comment by fraoustin** [comment]
Hi
I don't use mysql ... 
Do you have a working redmine with mysql (on aws) ?
Normally, the plugin installer use the same connection of redmine

Why redmine use a local Mysql and not remote (with IP:PORT 127.0.0.1:3306) ?

**Comment by mesolis** [comment]
i have redmine on a lightsail instance

we moved the db out of the server and it is mounted in rds in case it is necessary to scale

**Comment by fraoustin** [comment]
And the redmine works? (except plugin) and the error from the plugin agile (not redmine_indicator)

**Comment by mesolis** [comment]
run without any problem

(or at least they have not reported any error)

**Comment by fraoustin** [comment]
In your log, the error come from the redmine_agile (not redmine_indicator)
![image](https://user-images.githubusercontent.com/3457495/100703333-9789ac00-33a3-11eb-94e6-75b21869baeb.png)

I don't specific a link database in the redmine_indicator

**Comment by mesolis** [comment]
but when I tried to install the redmine_indicator I got the error, previously I had already installed another plugin (redmine_status) and it didn't give me the mysql error: /

**Comment by fraoustin** [comment]
Hi
you have the same problem with different plugins?
If this response is yes .... I think that the problem come from your installation

**Comment by mesolis** [comment]
Hi!

the problem is only with the redmine_indicator :/ when i exec 
"sudo rake redmine:plugins:migrate NAME=redmine_indicator"
and I get the mysql error: /

**Comment by fraoustin** [comment]
Sorry but i don't have a solution ... can you give me the name of other plugins (with link)?

**Comment by mesolis** [comment]
I already found the error, I need to put the enviroment !

thanks for helping me with the error
so I solved it
"bundle exec rake redmine: plugins: migrate NAME = redmine_indicator RAILS_ENV = production"

thnks bro!
