### ISSUE TITLE
Charts aren't shown

### ISSUE THREAD

**Issue by rzucatti** [fraoustin/redmine_indicator#18]
Hi!
I installed this plugin today on a bitnami redmine package, and when testing, the charts aren't shown in My Page. Inside Project, after configured, they are not shown either.

Went to access.log and saw this:
"GET /plugin_assets/redmine_indicator/javascripts/Chart.min.js HTTP/1.1" 404 196

How to fix it?
Thanks a lot.

**Comment by fraoustin** [comment]
Can you check that Chart.min.js exist in your install ...

**Comment by rzucatti** [comment]
Hi, @fraoustin ! Sorry for the delay.
I've checked out the file and yes, it is in htdocs\plugins\redmine_indicator\assets\javascripts.

Thank you for answering.

Edit: try to copy entire folder to /htdocs/plugin_assets/redmine_indicator/javascripts/ but same error.

**Comment by fraoustin** [comment]
Ok, I don't understand the origin of the mistake. Have you Chart.min.js in directory "/usr/src/redmine/plugins/redmine_indicator/assets/javascripts"?

**Comment by rzucatti** [comment]
My redmine is a Bitnami package installed on Windows, the javascripts folder is in:
D:\Bitnami\redmine-4.2.3-0\apps\redmine\htdocs\plugins\redmine_indicator\assets\javascripts
The file Chart.min.js is in this folder, I can open and read it's content (entire content on a single line).

**Comment by fraoustin** [comment]
Have you installed others plugins ?

**Comment by rzucatti** [comment]
Yes, I installed two other plugins and they work normally.

**Comment by fraoustin** [comment]
Bitnami use a specific version of redmine ... sorry
