### ISSUE TITLE
Issue with my_due_issue list

### ISSUE THREAD

**Issue by mauriziotallarico** [fraoustin/redmine_indicator#2]
Hi again,
i'm experiencing Redmine Error 500 when i've tried to add the "my_due_issue" to my home page.

> undefined local variable or method `link_to_context_menu' for #<#<Class:0xb3c24ae4>:0xb2507d0c> Did you mean? link_to_next_page
If you want i can provide also full redmine error log.

Thanks!

**Comment by fraoustin** [comment]
Your redmine is 3.4?

**Comment by mauriziotallarico** [comment]
Yes

Il ven 10 gen 2020, 10:03 fraoustin <notifications@github.com> ha scritto:

**Comment by fraoustin** [comment]
I use docker

my dockerfile

`
FROM redmine:3.4
WORKDIR /usr/src/redmine/plugins
RUN git clone https://github.com/fraoustin/redmine_indicator.git
WORKDIR /usr/src/redmine/
`
and i cannot to reproduce this bug.
You have a same message for all  "add" in "my page" or only "my_due_issue"?
what is the language for your profil?

**Comment by mauriziotallarico** [comment]
language is english. i've added with success other indicators like issues by status and by priority. only problem is with my_due issues

**Comment by fraoustin** [comment]
do you have more logs ?
my_due_issues is not specific element ...

**Comment by mauriziotallarico** [comment]
Here below full error log:

Error log

        /var/www/redmine/plugins/redmine_indicator/app/views/issues/_list_without_head.html.erb:26:in `block (2 levels) in _8ccbc0c4ce1a8c7f650e6be8d8b8e59f'
/var/www/redmine/app/helpers/issues_helper.rb:41:in `block in grouped_issue_list'
/var/www/redmine/app/helpers/queries_helper.rb:140:in `block in grouped_query_results'
/var/www/redmine/app/helpers/queries_helper.rb:125:in `each'
/var/www/redmine/app/helpers/queries_helper.rb:125:in `grouped_query_results'
/var/www/redmine/app/helpers/issues_helper.rb:37:in `grouped_issue_list'
/var/www/redmine/plugins/redmine_indicator/app/views/issues/_list_without_head.html.erb:9:in `block in _8ccbc0c4ce1a8c7f650e6be8d8b8e59f'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
/usr/local/rvm/gems/ruby-2.3.1/gems/haml-5.0.4/lib/haml/helpers/action_view_xss_mods.rb:6:in `with_output_buffer_with_haml_xss'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:38:in `capture'
/usr/local/rvm/gems/ruby-2.3.1/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:47:in `capture_with_haml'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/helpers/form_tag_helper.rb:70:in `form_tag'
/usr/local/rvm/gems/ruby-2.3.1/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:122:in `form_tag_with_haml'
/usr/local/rvm/gems/ruby-2.3.1/gems/haml-5.0.4/lib/haml/helpers/action_view_xss_mods.rb:19:in `form_tag_with_haml_xss'
/var/www/redmine/plugins/redmine_indicator/app/views/issues/_list_without_head.html.erb:4:in `_8ccbc0c4ce1a8c7f650e6be8d8b8e59f'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/deface-1.3.0/lib/deface/action_view_extensions.rb:41:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:25:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/usr/local/rvm/gems/ruby-2.3.1/bundler/gems/prototype-rails-0fed929ff48c/lib/prototype-rails/rendering.rb:8:in `render_with_update'
/usr/local/rvm/gems/ruby-2.3.1/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:14:in `render'
/var/www/redmine/plugins/redmine_indicator/app/views/my/_my_block_issues.html.erb:25:in `_38b97bc7df90fcc5ffe42d8a02ecd500'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/deface-1.3.0/lib/deface/action_view_extensions.rb:41:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:25:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/usr/local/rvm/gems/ruby-2.3.1/bundler/gems/prototype-rails-0fed929ff48c/lib/prototype-rails/rendering.rb:8:in `render_with_update'
/usr/local/rvm/gems/ruby-2.3.1/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:14:in `render'
/var/www/redmine/plugins/redmine_indicator/app/views/my/blocks/_my_issues_due.html.erb:12:in `_f58cc4ca64d68e36e48fdbbef1ec4795'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/deface-1.3.0/lib/deface/action_view_extensions.rb:41:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/partial_renderer.rb:309:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:51:in `render_partial'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:25:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/usr/local/rvm/gems/ruby-2.3.1/bundler/gems/prototype-rails-0fed929ff48c/lib/prototype-rails/rendering.rb:8:in `render_with_update'
/usr/local/rvm/gems/ruby-2.3.1/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:14:in `render'
/var/www/redmine/app/helpers/my_helper.rb:58:in `render_block_content'
/var/www/redmine/app/helpers/my_helper.rb:35:in `render_block'
/var/www/redmine/app/helpers/my_helper.rb:27:in `block in render_blocks'
/var/www/redmine/app/helpers/my_helper.rb:26:in `each'
/var/www/redmine/app/helpers/my_helper.rb:26:in `render_blocks'
/var/www/redmine/app/views/my/page.html.erb:13:in `block in _6fd3d1ff2c739edc896930410c7ebece'
/var/www/redmine/app/views/my/page.html.erb:11:in `each'
/var/www/redmine/app/views/my/page.html.erb:11:in `_6fd3d1ff2c739edc896930410c7ebece'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/deface-1.3.0/lib/deface/action_view_extensions.rb:41:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:14:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:46:in `render_template'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:27:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/rendering.rb:100:in `_render_template'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/rendering.rb:83:in `render_to_body'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/abstract_controller/rendering.rb:25:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:16:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:43:in `render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/var/www/redmine/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-raw-upload-1.1.1/lib/rack/raw_upload.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.11/lib/rack/etag.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.11/lib/rack/conditionalget.rb:25:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.11/lib/rack/head.rb:13:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:225:in `context'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:220:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/var/www/redmine/plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/query_cache.rb:36:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.11/lib/rack/methodoverride.rb:22:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.11/lib/rack/runtime.rb:18:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.11/lib/rack/content_length.rb:15:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/rack-1.6.11/lib/rack/sendfile.rb:113:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `public_send'
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.8/lib/rails/railtie.rb:194:in `method_missing'
/usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.3.1/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.3.1/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.3.1/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.3.1/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/usr/local/rvm/gems/ruby-2.3.1/gems/passenger-5.3.1/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by fraoustin** [comment]
Can you test a new version 0.2.7, please?
Thank you

**Comment by mauriziotallarico** [comment]
Hello,
i confirm that 0.27 is working now, as usually many thanks!
Maurizio
