### ISSUE TITLE
 What version of redmine is supported?

### ISSUE THREAD

**Issue by Jonixxz** [fraoustin/redmine_indicator#3]
I tried to install it in version 4.0.2 of Redmine but it didn't work.

**Comment by fraoustin** [comment]
Hi, I use this plugin with redmine 4.0.1 and 4.1.0 without problem

Have you a message? what is your platform?

**Comment by Jonixxz** [comment]
Hi, it worked! I had to modify the command
class IndicatorCustomFields <ActiveRecord :: Migration
 by
 class IndicatorCustomFields <ActiveRecord :: Migration[5.2]

A query can other indicators be added or existing ones modified with values ​​that interest me?

**Comment by fraoustin** [comment]
Hi
today ... no but if you have some ideas, i can to add for all
You can create a Issues by indicator
Thank you for your contribution

**Comment by mangelozzi** [comment]
> Hi, it worked! I had to modify the command
> class IndicatorCustomFields <ActiveRecord :: Migration
>  by
>  class IndicatorCustomFields <ActiveRecord :: Migration [5.2]
> 
> A query can other indicators be added or existing ones modified with values ​​that interest me?

Please Note it should be (no space before `[5.2]`):

    class IndicatorCustomFields <ActiveRecord :: Migration[5.2]
