### ISSUE TITLE
add russian translation

### ISSUE THREAD

**Issue by Luckyvb** [fraoustin/redmine_indicator#5]
`diff --git a/config/locales/ru.yml b/config/locales/ru.yml
new file mode 100755
index 0000000..e9a03d1
--- /dev/null
+++ b/config/locales/ru.yml
@@ -0,0 +1,12 @@
+ru:
+  my_issues_due: "Мои просроченные задачи"
+  my_issues_today : "Мои задачи на сегодня"
+  my_issues_next : "Мои следующие задачи"
+  issues_due: "Просроченные задачи"
+  issues_today : "Задачи на сегодня"
+  issues_next : "Следующие задачи"
+  my_issues_opened_closed_today : " Мои открытые и закрытые задачи за сегодня"
+  my_issues_summary : "Сводка по моим задачам"
+  my_issues_by_priority : "Мои задачи по приоритету"
+  my_issues_by_status : "Мои задачи по статусу"
+  my_issues_by_tracker : "Мои задачи по трекеру"
`

**Comment by fraoustin** [comment]
Hi Luckyvb, 
It is a good new to add russian .
Can you propose a pull request or I add your code in new version 0.2.12 ?

**Comment by fraoustin** [comment]
I created the tag 0.2.12
Thank you for your help
