### ISSUE TITLE
Project Page does not appear ? :Help Wanted

### ISSUE THREAD

**Issue by konpega** [fraoustin/redmine_indicator#6]
Hi first of all this plug in is wonderfull. My Page is OK.
Should I make an adjustment for the project page? Because I couldn't see the screen as you show in scrshot.
![image](https://user-images.githubusercontent.com/61666724/81157886-1b0b2800-8f90-11ea-9f36-1ad6c7818211.png)

![image](https://user-images.githubusercontent.com/61666724/81158050-44c44f00-8f90-11ea-8fea-e4b15b8350c8.png)

**Comment by fraoustin** [comment]
Hi 
thank you for your message
have you a log of redmine?

can you check CustomField for project (http://<url>//custom_fields?tab=ProjectCustomField) and check indicator* (check visible for your)

Can you with admin login?

**Comment by fraoustin** [comment]
I check version 0.2.12 with docker

My Dockerfile is

> FROM redmine
> WORKDIR /usr/src/redmine/plugins
> RUN git clone https://github.com/fraoustin/redmine_indicator.git
> WORKDIR /usr/src/redmine/

and load with

> docker build -t myredmine .
> docker run -d -p 3000:3000 -e REDMINE_PLUGINS_MIGRATE=1 --name myredmine myredmine

And all it's ok ...

**Comment by konpega** [comment]
This is screenshot from Custom Field.




I am working on Windows 8 and using Bitnami RedminePlusAgile 4.1.0-8


Where should I check?



    6 Mayıs 2020 Çarşamba 13:01:38 GMT+3 tarihinde, fraoustin <notifications@github.com>şunu yazdı:  
 
 


I check version 0.2.12 with docker

My Dockerfile is


FROM redmine
WORKDIR /usr/src/redmine/plugins
RUN git clone https://github.com/fraoustin/redmine_indicator.git
WORKDIR /usr/src/redmine/


and load with


docker build -t myredmine .
docker run -d -p 3000:3000 -e REDMINE_PLUGINS_MIGRATE=1 --name myredmine myredmine


And all it's ok ...

**Comment by fraoustin** [comment]
Can you a screenshot of http://<your_url>/custom_fields?tab=ProjectCustomField

Have you a log of redmine when redmine start ?

**Comment by fraoustin** [comment]
You are connected as "admin"?

**Comment by konpega** [comment]
Hi fraoustin,
I am working on laptop (127.0.0.1 :)). I am using it as admin. Soryy but I could not catch the log file. If you told me the name of it. I can send it also.
    6 Mayıs 2020 Çarşamba 18:34:48 GMT+3 tarihinde, fraoustin <notifications@github.com>şunu yazdı:  
 
 


You are connected as "admin"?

**Comment by fraoustin** [comment]
in your log directory ... 

can you make a screenshot of http://<your_url>/custom_fields?tab=ProjectCustomField

**Comment by konpega** [comment]
[access.log](https://github.com/fraoustin/redmine_indicator/files/4593272/access.log)
[error.log](https://github.com/fraoustin/redmine_indicator/files/4593273/error.log)
[install.log](https://github.com/fraoustin/redmine_indicator/files/4593274/install.log)

These are the log files. I hope they are the correct ones

**Comment by fraoustin** [comment]
it's mysterious ... the plugin is ok: because you can view graphic ... it's is necessary to check in configuration of admin , the  CustomField menu

click on administration and after on Custom Fields

![image](https://user-images.githubusercontent.com/3457495/81310378-4b33f300-9084-11ea-97f1-d0d8e2fb7cac.png)

click on Project
![image](https://user-images.githubusercontent.com/3457495/81310449-5f77f000-9084-11ea-8836-25192c120b0a.png)

click on indicator_left_top
![image](https://user-images.githubusercontent.com/3457495/81310507-73235680-9084-11ea-8895-71daec7f20c9.png)

**Comment by konpega** [comment]
I believe so.

![image](https://user-images.githubusercontent.com/61666724/81322352-85a98a00-909c-11ea-9ec7-c254966c95f2.png)

![image](https://user-images.githubusercontent.com/61666724/81322431-a245c200-909c-11ea-943f-7f56882cd907.png)

How come?

Should I upload the plugin one more time?

**Comment by konpega** [comment]
I think I have to apologize.  I created manually one custom area by looking at the table you send. 
I miss one point I think. Should we create these custom fields by hand?

![image](https://user-images.githubusercontent.com/61666724/81323309-dcfc2a00-909d-11ea-8719-7944497c8a85.png)

**Comment by fraoustin** [comment]
Normally no ... how do you have installed the plugin? have you load the plugin migration? (it is the normal procedure for add a plugin in your system https://www.redmine.org/projects/redmine/wiki/Plugins or https://github.com/fraoustin/redmine_indicator#installation)

> rake redmine:plugins:migrate NAME=redmine_indicator

If you have not load the plugin migration, you can add the fields indicator_left_top, indicator_left_bottom and indicator right

![image](https://user-images.githubusercontent.com/3457495/81325021-12057e00-9098-11ea-814a-b40396d5cbee.png)

**Comment by konpega** [comment]
I tried one more time and I got some warnings during the migration. Normally mysqldatabase has some password !

![image](https://user-images.githubusercontent.com/61666724/81333981-fdcc7b80-90ad-11ea-89c1-429430a8fc2c.png)

May I ask a question whhat is the difference between two commands?
rake redmine:plugins:migrate NAME=redmine_indicator
and
bundle exec rake redmine:plugins:migrate NAME=redmine_indicator RAILS_ENV=production

**Comment by konpega** [comment]
Hi fraoustin

You are right and plugin installed correctly. To see and be sure I deleted the data completely. Just install all plugins and push the new Project button. Result is as seen. There the modules. 
I am using the commands  (I copied from the redmine manuals)
for backup       **"mysqldump -A -u root -p > backup.sql"**
for upload        **"mysql -u root -p -D bitnami_redmine < bitnami_redmine.sql" command.**
These commands are causing the fault.

I should find a way to migrate my data. 

![image](https://user-images.githubusercontent.com/61666724/81374217-66941200-9107-11ea-89fc-2796f461b9b7.png)

**Comment by fraoustin** [comment]
Ok, i understand 
If you want , i can search in your backup.sql the reason of the problem (objective : check the problem is the backup or the restore)

**Comment by konpega** [comment]
You are so kind but I am a worker and if I share (I believe this is not secret data) this may cause to loose my job. I am not granted. I will try to get the data from the server mysqldump (without -A). Make sense?
II could not enter localhost\phpmyadmin  page. If I could I will try from that page to backup the database and upload.
Murphy is on duty.
    8 Mayıs 2020 Cuma 09:36:12 GMT+3 tarihinde, fraoustin <notifications@github.com>şunu yazdı:  
 
 


Ok, i understand
If you want , i can search in your backup.sql the reason of the problem (objective : check the problem is the backup or the restore)

**Comment by fraoustin** [comment]
ok
you can check found "indicator_left_top" in your backup.sql ... if you found the problem is in restore , else the problem is in backup.
I don't know mysql ... sorry

**Comment by konpega** [comment]
I created manually custom fields in your plugin and it is solved. On the main page of the project, I manage to show the statistics.

![image](https://user-images.githubusercontent.com/61666724/81421237-cfa47580-9159-11ea-8dfb-5678dab807a3.png)
